### ISSUE TITLE
Webinspect Config errors on Package Resources

### ISSUE THREAD

**Issue by xolian** [target/webbreaker#10] opened 2017-09-07 18:12 UTC
`webbreaker/webbreakercli webinspect scan --settings example`, accessing configs in Python package resources from the [webbreaker egg](http://peak.telecommunity.com/DevCenter/PythonEggs#accessing-package-resources).  The anticipated behavior should be from the filesystem under `webbreaker/etc/webinspect`, unless an absolute path is declared in the `--settings`.

**Comment by mdunaj** [comment] 2017-09-11 13:32
This was a duplicate of Issue #6

**Closed by mdunaj** 2017-09-11 13:32 UTC
